CREATE VIEW view_name AS
SELECT comlumn1, column2...
FROM table_name
where condition;


-- Listar o nome, o sobrenome, e a data de contratação dos funcionários que não são comissionados:
CREATE OR REPLACE VIEW V_UNCOMMISSIONED_EMPLOYEES AS 
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
FROM hr.EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

SELECT * FROM V_UNCOMMISSIONED_EMPLOYEES;

--

CREATE OR REPLACE VIEW V_EMPLOYEES_FUNCTIONS AS 
SELECT FIRST_NAME || ' ' || LAST_NAME AS NOME_COMPLETO, JOB_TITLE FUNCAO, PHONE_NUMBER FONE, HIRE_DATE DT_CONTRATACAO
FROM HR.EMPLOYEES E INNER JOIN HR.JOBS J ON E.JOB_ID = J.JOB_ID;

SELECT * FROM V_EMPLOYEES_FUNCTIONS;    

--- VIEW SIMPLES -> RECUPERA LINHAS DE UMA ÚNICA TABELA 
--- VIEW COMPLEXA -> RECUPERA LINHAS DE VÁRIAS TABELAS

-- View que só aceita leitura
CREATE VIEW EMP_GEP_CONST AS 
    SELECT EMPLOYEE_ID, LAST_NAME, salary
    FROM EMPLOYEES
WITH READ ONLY CONSTRAINT APENAS_LEITURA;

CREATE VIEW EMP_DEP_OPTION_CONST AS 
    SELECT EMPLOYEE_ID, LAST_NAME, SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 20
    WITH CHECK OPTION CONSTRAINT emp_20;